services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: dusk_user
      POSTGRES_PASSWORD: sMlJrjwrK47eCTiLdr6OqYX79pCIqh
      POSTGRES_DB: dusk
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
